### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rohanchn** [PonteIneptique/YALTAi#10]
Hi @PonteIneptique,

I tried to set it up, but got the following error:

`
ModuleNotFoundError: No module named 'pytorch_lightning.callbacks.progress.base'
`

Is it somehow linked to the very recent progress bar changes in `kraken` not up to date here?

**Comment by PonteIneptique** [comment]
I'll upload a fix today 😁

**Comment by rohanchn** [comment]
Perfect! Excited to finally run some tests. Thank you!

**Comment by PonteIneptique** [comment]
Can you try YALTAi==0.1.3 (just released) ? I have no GPU at hand ^^

**Comment by rohanchn** [comment]
I did, and the installation went through, with `kraken==4.3.10` Previously I had `kraken==4.3.6`

But now I have this error:

`UserWarning: Failed to load image Python extension: '/home/rohan/codes/YALTAi/venv/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Segmentation fault (core dumped)
`

I looked up `libjpeg` and `libpng` through `pip`, but couldn't find helpful clues.

**Comment by PonteIneptique** [comment]
The warning and the segmentation fault might be disconnected...
Did you reinstall from scratch ?

**Comment by rohanchn** [comment]
I just did, and now it's training. Thank you! 

I have two more questions: Can I use a `manifest file` instead of `PATH/TO/ALTOorPAGE/*.xml`?
Can I use the model to infer regions in eScriptorium?

**Comment by PonteIneptique** [comment]
> I have two more questions: Can I use a manifest file instead of PATH/TO/ALTOorPAGE/*.xml?

Can you give me more details about this question ? Which command are you talking about ^^

> Can I use the model to infer regions in eScriptorium?

As of now, no, unfortunately. I usually segment locally and then upload on eScriptorium.

There is a roadmap on how to do it ( https://gitlab.com/scripta/escriptorium/-/issues/703 ) but I have not had the time to deal with it...

**Comment by PonteIneptique** [comment]
> Can you give me more details about this question ? Which command are you talking about ^^

I am a bit stupid, that's my own example...

`yaltai alto-to-yolo PATH/TO/ALTOorPAGE/*.xml my-dataset --shuffle .1 --segmonto region`

I think, I might be wrong, but shuffle is optional. It means you can have a full convert and then split yourself.
If you want to provide an option to use a manifest, please send it my way through PR ;)

**Comment by rohanchn** [comment]
The one that converts from alto/page to yolov5 format:
`yaltai alto-to-yolo PATH/TO/ALTOorPAGE/*.xml my-dataset --shuffle .1 --segmonto region`
So to reframe: can I use a `manifest file` instead of  `PATH/TO/ALTOorPAGE/*.xml` in this command?

> As of now, no, unfortunately. I usually segment locally and then upload on eScriptorium.

Thanks for the tip! That sounds doable. I can just pass a zip file in `import transcriptions`

**Comment by rohanchn** [comment]
> If you want to provide an option to use a manifest, please send it my way through PR ;)

Right, let me develop the intitution for it first.

**Comment by PonteIneptique** [comment]
> Right, let me develop the intuition for it first.

Do not worry about it, and sorry, it might have sounded aggressive, but it was not my intention. It was my way to say "Contributions are welcome" ^^'

**Comment by rohanchn** [comment]
It sounded very normal. Please don't apologize. Looking forward to learn more!
