### ISSUE TITLE
Finetuning YOLOV5-OBB

### ISSUE THREAD

**Issue by rohanchn** [PonteIneptique/YALTAi#13]
Hi @PonteIneptique, 

I did some training with the usual v5x6 model, and initial tests suggests very good results. Here's an example of assesment during validation.
![seg](https://user-images.githubusercontent.com/52149584/234019480-8ea0a79d-d56c-4185-a205-4150fff6b21f.png)

However, I also think my data may benefit from rotating bounding boxes (as deskew on two facing pages in one image could be a problem, and also the way `GraphicZone` appear in my data), so thought I'd also test YOLOv5-OBB that you mention in the Yaltai paper. 

I have a couple of questions:
1. How do I get the YOLOv5-OBB model?

2. Do you think a baseline model trained in `ketos segtrain` with `--suppress-regions` could be more efficient than `--no-suppress-regions` for a Yaltai > Kraken pipeline?

**Comment by PonteIneptique** [comment]
Hi ^^

So, first of all, to address one elephant in the room, as lines are anchored based on their center, deskewing is mostly useless if what you are looking into is have you line correctly ordered in different columns.

1. YOLO OBB is here: https://github.com/hukaixuan19970627/yolov5_obb/ but I would have to adapt the Alto to YOLO to produce oriented box.
2. Yes, it simply produces less to postprocess :)

**Comment by rohanchn** [comment]
Right, I thought so too. 

Thanks! I got the same link but couldn't get myself to trust what I was looking, so posted here.

**Comment by PonteIneptique** [comment]
FYI, I am looking to implement yolo8 models but I need to check before if they work well :)

**Comment by rohanchn** [comment]
Isn't that the latest release? Sounds something I will look forward to try!

**Comment by rohanchn** [comment]
`pip install YALTAi` doesn't reflect the latest changes vis-a-vis manifest. You may want to tag a new release.

**Comment by PonteIneptique** [comment]
@rohanchn You might be interested in knowing I moved YALTAi to YOLOv8 which allows for polygons. I have not tested polygon yet (and YALTAi does not allows for Polygons yet), but it might be a solution for this :)

**Comment by rohanchn** [comment]
Thank you! I should be able to test soon.

**Comment by CrazyCrud** [comment]
@PonteIneptique Sorry, for commenting on a closed issue, but I would like to ask something about the original question. First of all, thank you very much for this library and the work you put in!      

Is it now possible to rotate bounding boxes or even use polygons that are processed?

Thank you very much in advance!

Best regards
Constatnin
