### ISSUE TITLE
pip subprocess to install build dependencies did not run successfully

### ISSUE THREAD

**Issue by trishaoconnor** [PonteIneptique/YALTAi#14]
Hello @PonteIneptique,

Thank you for sharing this code it is really useful. I am not sure if this is the correct forum for this but I received an error while following the instructions and thought that it might be useful to flag it here. 

I'm using Anaconda and have created an environment but when I enter the run command I get the error `pip subprocess to install build dependencies did not run successfully` proceeded by the lines of output copied below. I apologise for copying it all below, I was just hoping that you may spot something, a likely error from the output that I have not. 

Apologies again if this is not the correct forum for posting this issue. 

`  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [347 lines of output]
      Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting setuptools
        Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Collecting Cython>=0.29.13
        Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.0
        Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        python setup.py bdist_wheel did not run successfully.
        exit code: 1

        [292 lines of output]
        Running from numpy source directory.
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        blis_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries blis not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_3_10_blas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_blas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        C:\Users\trish\AppData\Local\Temp\pip-install-afdjf47l\numpy_43ccd1b8d6294d61826b697040da0bd2\numpy\distutils\system_info.py:690: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          self.calc_info()
        blas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries blas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        C:\Users\trish\AppData\Local\Temp\pip-install-afdjf47l\numpy_43ccd1b8d6294d61826b697040da0bd2\numpy\distutils\system_info.py:690: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          self.calc_info()
        blas_src_info:
          NOT AVAILABLE

        C:\Users\trish\AppData\Local\Temp\pip-install-afdjf47l\numpy_43ccd1b8d6294d61826b697040da0bd2\numpy\distutils\system_info.py:690: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          self.calc_info()
          NOT AVAILABLE

        'svnversion' is not recognized as an internal or external command,
        operable program or batch file.
        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_clapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas,lapack not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        flame_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries flame not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\Library\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\Users\trish\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\Library\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\Users\trish\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\Library\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\trish\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\Users\trish\anaconda3\envs\rescape\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\Users\trish\anaconda3\envs\rescape\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\Users\trish\anaconda3\Library\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\Users\trish\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack not found in ['C:\\Users\\trish\\anaconda3\\envs\\rescape\\lib', 'C:\\', 'C:\\Users\\trish\\anaconda3\\envs\\rescape\\libs', 'C:\\Users\\trish\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        C:\Users\trish\AppData\Local\Temp\pip-install-afdjf47l\numpy_43ccd1b8d6294d61826b697040da0bd2\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
        lapack_src_info:
          NOT AVAILABLE

        C:\Users\trish\AppData\Local\Temp\pip-install-afdjf47l\numpy_43ccd1b8d6294d61826b697040da0bd2\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
          NOT AVAILABLE

        C:\Users\trish\anaconda3\envs\rescape\lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running bdist_wheel
        running build
        running config_cc
        unifing config_cc, config, build_clib, build_ext, build commands --compiler options
        running config_fc
        unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.9
        creating build\src.win-amd64-3.9\numpy
        creating build\src.win-amd64-3.9\numpy\distutils
        building library "npymath" sources
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error

        python setup.py clean did not run successfully.
        exit code: 1

        [10 lines of output]
        Running from numpy source directory.

        `setup.py clean` is not supported, use one of the following instead:

          - `git clean -xdf` (cleans all files)
          - `git clean -Xdf` (cleans all versioned files, doesn't touch
                              files that aren't checked into the git repo)

        Add `--force` to your command to use it anyway if you must (unsupported).

        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by PonteIneptique** [comment]
The issue is I don't use conda... So I'll have to test conda when I come back home. It might be failing to compile stuff.

can you try `conda install yaltai` ?

**Comment by trishaoconnor** [comment]
Thank you so much for your swift response. You're very kind. Unfortunately, that did not work. 
`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - yaltai

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by trishaoconnor** [comment]
I tried in Linux and this is the error that I got:

`trishaoconnor@LAPTOP-1MCOOMIH:/mnt/c/Users/trish/GitHub/Rescape$ pip install YALTAi
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
trishaoconnor@LAPTOP-1MCOOMIH:/mnt/c/Users/trish/GitHub/Rescape$ sudo apt install python3-pip
[sudo] password for trishaoconnor:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  build-essential bzip2 cpp cpp-11 dpkg-dev fakeroot fontconfig-config fonts-dejavu-core g++ g++-11 gcc
  gcc-11 gcc-11-base javascript-common libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libasan6 libatomic1 libc-dev-bin libc-devtools libc6-dev libcc1-0 libcrypt-dev
  libdeflate0 libdpkg-perl libexpat1 libexpat1-dev libfakeroot libfile-fcntllock-perl libfontconfig1
  libfreetype6 libgcc-11-dev libgd3 libgomp1 libisl23 libitm1 libjbig0 libjpeg-turbo8 libjpeg8 libjs-jquery
  libjs-sphinxdoc libjs-underscore liblsan0 libmpc3 libnsl-dev libpython3-dev libpython3.10
  libpython3.10-dev libpython3.10-minimal libpython3.10-stdlib libquadmath0 libstdc++-11-dev libtiff5
  libtirpc-dev libtsan0 libubsan1 libwebp7 libxpm4 linux-libc-dev lto-disabled-list make manpages-dev
  python3-dev python3-distutils python3-lib2to3 python3-pkg-resources python3-setuptools python3-wheel
  python3.10 python3.10-dev python3.10-minimal rpcsvc-proto zlib1g-dev
Suggested packages:
  bzip2-doc cpp-doc gcc-11-locales debian-keyring g++-multilib g++-11-multilib gcc-11-doc gcc-multilib
  autoconf automake libtool flex bison gdb gcc-doc gcc-11-multilib apache2 | lighttpd | httpd glibc-doc bzr
  libgd-tools libstdc++-11-doc make-doc python-setuptools-doc python3.10-venv python3.10-doc binfmt-support
The following NEW packages will be installed:
  build-essential bzip2 cpp cpp-11 dpkg-dev fakeroot fontconfig-config fonts-dejavu-core g++ g++-11 gcc
  gcc-11 gcc-11-base javascript-common libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libasan6 libatomic1 libc-dev-bin libc-devtools libc6-dev libcc1-0 libcrypt-dev
  libdeflate0 libdpkg-perl libexpat1-dev libfakeroot libfile-fcntllock-perl libfontconfig1 libfreetype6
  libgcc-11-dev libgd3 libgomp1 libisl23 libitm1 libjbig0 libjpeg-turbo8 libjpeg8 libjs-jquery
  libjs-sphinxdoc libjs-underscore liblsan0 libmpc3 libnsl-dev libpython3-dev libpython3.10-dev libquadmath0
  libstdc++-11-dev libtiff5 libtirpc-dev libtsan0 libubsan1 libwebp7 libxpm4 linux-libc-dev
  lto-disabled-list make manpages-dev python3-dev python3-distutils python3-lib2to3 python3-pip
  python3-setuptools python3-wheel python3.10-dev rpcsvc-proto zlib1g-dev
The following packages will be upgraded:
  libexpat1 libpython3.10 libpython3.10-minimal libpython3.10-stdlib python3-pkg-resources python3.10
  python3.10-minimal
7 upgraded, 68 newly installed, 0 to remove and 95 not upgraded.
Need to get 28.7 MB/79.7 MB of archives.
After this operation, 242 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10 amd64 3.10.6-1~22.04.2ubuntu1
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10 amd64 3.10.6-1~22.04.2ubuntu1
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-stdlib amd64 3.10.6-1~22.04.2ubuntu1
Ign:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-minimal amd64 3.10.6-1~22.04.2ubuntu1
Ign:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-minimal amd64 3.10.6-1~22.04.2ubuntu1
Ign:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 linux-libc-dev amd64 5.15.0-71.78
Ign:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libstdc++-11-dev amd64 11.3.0-1ubuntu1~22.04
Ign:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 g++-11 amd64 11.3.0-1ubuntu1~22.04
Ign:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-dev amd64 3.10.6-1~22.04.2ubuntu1
Ign:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.6-1~22.04.2ubuntu1
Ign:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-pip all 22.0.2+dfsg-1ubuntu0.2
Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10 amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10 amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:3 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-stdlib amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:4 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-minimal amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:5 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-minimal amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:6 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 linux-libc-dev amd64 5.15.0-71.78
  404  Not Found [IP: 185.125.190.39 80]
Err:7 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libstdc++-11-dev amd64 11.3.0-1ubuntu1~22.04
  404  Not Found [IP: 185.125.190.39 80]
Err:8 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 g++-11 amd64 11.3.0-1ubuntu1~22.04
  404  Not Found [IP: 185.125.190.39 80]
Err:9 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-dev amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:10 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.6-1~22.04.2ubuntu1
  404  Not Found [IP: 185.125.190.39 80]
Err:11 http://security.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-pip all 22.0.2+dfsg-1ubuntu0.2
  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/libpython3.10_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/python3.10_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/libpython3.10-stdlib_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/python3.10-minimal_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/libpython3.10-minimal_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-71.78_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-11/libstdc%2b%2b-11-dev_11.3.0-1ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-11/g%2b%2b-11_11.3.0-1ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/libpython3.10-dev_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.10/python3.10-dev_3.10.6-1%7e22.04.2ubuntu1_amd64.deb  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python-pip/python3-pip_22.0.2%2bdfsg-1ubuntu0.2_all.deb  404  Not Found [IP: 185.125.190.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by PonteIneptique** [comment]
Discussed and resolved outside Github
