### ISSUE TITLE
Ultralytics warning on an epoch during training: "NMS time limit 1.300s exceeded"

### ISSUE THREAD

**Issue by rohanchn** [PonteIneptique/YALTAi#19]
While training v8m I get tthe following warning on each epoch: `NMS time limit 1.300s exceeded` 

Have you seen this one before?

I did some digging and noticed this [issue](https://github.com/ultralytics/yolov5/issues/7390). From the comments, it looks like the calculation is happening as usual, and the warning only suggests that the processing took longer than the set time limit, which we can also modify. Is this normal behaviour?

**Comment by PonteIneptique** [comment]
This is a Yolo issue and less of a YALTAi issue, i can't answer to you unfortunately, as I don't have the answer.

**Comment by rohanchn** [comment]
I suspect this should go away if I modify the default time limit in ultralytics/yolo as exaplined in the linked issue above; perhaps I will try after the ongoing training run.
