### ISSUE TITLE
Problem with Segmonto regions using subtypes 

### ISSUE THREAD

**Issue by PaulineJac** [PonteIneptique/YALTAi#4]
Hello, 

First of all, I would like to thank you for this beneficial tool. I have tried to use the tool with a segmentation that uses the Segmonto vocabulary ([here](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/tree/main/Grountruth/Data) is the data). 
Unfortunately, during the transformation, only the regions without subtypes are kept: 
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/61355979/199546753-2aa07aad-d306-4c4d-bc2b-b74528215807.png">

How can I remedy this? 
Thanks for your help, 
Pauline

**Comment by PonteIneptique** [comment]
Thanks @gabays ;)

**Comment by PaulineJac** [comment]
Wonderful. I will try it. Thank you very much for your quick answers.
