### ISSUE TITLE
Problem with segmentation

### ISSUE THREAD

**Issue by pkzli** [PonteIneptique/YALTAi#8]
Hi, I'm trying to do some segmentation using yaltai, however, when I run 

```
yaltai kraken --device cuda:0 -I "original/*.png" --suffix ".xml" segment --yolo /home/users/k/kuenzlip/GIT/yolov5/runs/train/exp5/weights/best.pt
```

I'm getting this kind of error

```
Loading ANN /home/users/k/kuenzlip/yaltai-env/lib/python3.8/site-packages/kraken/blla.mlmodel	Segmenting	Using cache found in /home/users/k/kuenzlip/.cache/torch/hub/ultralytics_yolov5_v6.2
YOLOv5 🚀 2023-2-2 Python-3.8.6 torch-1.11.0+cu102 CUDA:0 (NVIDIA TITAN RTX, 24220MiB)

Fusing layers... 
Model summary: 444 layers, 86200330 parameters, 0 gradients, 203.8 GFLOPs
Adding AutoShape... 
Segmenting original/document-060.png
/home/users/k/kuenzlip/yaltai-env/lib/python3.8/site-packages/kraken/lib/segmentation.py:234: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if l_point.type != 'Point':

✗
[02/02/23 17:58:22] ERROR    Failed processing original/document-060.png: 1                                                                                                            kraken_yaltai.py:201
Failed processing original/document-060.png: 1
```

Here the dependency file I'm using [yaltai-requirements.txt](https://github.com/PonteIneptique/YALTAi/files/10571574/yaltai-requirements.txt)

I'm very new to this tool, so maybe I'm doing something obviously wrong.

**Comment by PonteIneptique** [comment]
Hi :)
I am sorry for this bug, if only one file fails, then it's "ok". But basically, the issue comes from Kraken<4.2.0
I am waiting on the new release of Kraken (4.2.1) as 4.2.0 was quite buggy with the text. Hopefuly, once it's released, there won't be much work for me to do and we should be able to avoid such errors.

**Comment by pkzli** [comment]
Indeed I just tried with kraken 4.2.1.dev113 from master branch and it seems to solve the problem.

**Comment by PonteIneptique** [comment]
Note that there might be bugs because of the version change. It might fail
(if it doesn't, it's good news)

**Comment by PonteIneptique** [comment]
@pkzli This should now works with YALTAi v0.1.0
